### ISSUE TITLE
Does it support non latin characters?

### ISSUE THREAD

**Issue by asavchuk** [mandolyte/mdtopdf#10]
source
Влюбиться можно в красоту, но полюбить – лишь только душу!

result
Ð’Ð»ÑŽÐ±Ð¸Ñ‚ÑOEÑ•Ñ• Ð¼Ð¾Ð¶Ð½Ð¾ Ð² ÐºÑ€Ð°Ñ•Ð¾Ñ‚Ñƒ, Ð½Ð¾ Ð¿Ð¾Ð»ÑŽÐ±Ð¸Ñ‚ÑOE
â€“ Ð»Ð¸ÑˆÑOE Ñ‚Ð¾Ð»ÑOEÐºÐ¾ Ð´ÑƒÑˆÑƒ!

This is how it makes text with non latin characters. A required font is in the project folder and the font name is used in Styler options. How to fix it?

**Comment by mandolyte** [comment]
This is really a gofpdf question I think. I'm out of town without a
computer now. If you don't get an answer by the time I get back, I'll look
at it. After mid September...

**Comment by asavchuk** [comment]
here is a minimal example

https://gist.github.com/asavchuk/6743179b5dabac1cd7714d7f6255df6c

**Comment by asavchuk** [comment]
The Arial font I used supports glyphs of the needed language. If you need other font to try you could use this one https://github.com/googlefonts/AmaticSC/blob/master/fonts/ttf/AmaticSC-Regular.ttf 
It works when I use it with  https://github.com/signintech/gopdf

**Comment by mandolyte** [comment]
Thanks. I finally got gofpdf to work with Russian (https://gist.github.com/mandolyte/8cfcf664567eb098e762c668dac16782). Now I'll see what needs to be with my code to enable this. I used the Helvetica 1251 font provided by the gofpdf project. Let me know if you see anything else about this problem that would help.

**Comment by mandolyte** [comment]
I have filed an issue with the blackfriday markdown parser project: #russross/blackfriday/569

Their parser accepts only []byte as input and I don't see any way to workaround this.

**Comment by mandolyte** [comment]
Better understanding of how to use the PDF generator to apply fonts, codepages and then to use those in this package resulted in a solution.

The README now documents (at the end) how to do it. And the `cmd` folder has a complete working example using Russian. The example code is `russian.go`
