### ISSUE TITLE
support chinese?

### ISSUE THREAD

**Issue by carrymec** [mandolyte/mdtopdf#13]
how to setting to support chinese

**Comment by mandolyte** [comment]
@carrymec do you have an example of markdown in Chinese?  I will try to find one as well. 

What happens when you try it?

**Comment by emaer** [comment]
Example of markdown in Chinese: https://github.com/emaer/obsstudio-plugin/blob/master/README.md

thx

> @carrymec do you have an example of markdown in Chinese? I will try to find one as well.
> 
> What happens when you try it?

**Comment by mandolyte** [comment]
An example is now included.
