### ISSUE TITLE
Installing latest binary results with binary named "cmd", not "mdtopdf"

### ISSUE THREAD

**Issue by mandolyte** [mandolyte/mdtopdf#36]
@jessp01 - am I doing something wrong? Below is a transcript.

```sh
$ echo $GOBIN
/home/cecil/go/bin
$ go install github.com/mandolyte/mdtopdf/cmd@latest
$ mdtopdf -h
-bash: mdtopdf: command not found
$ ls $GOBIN
catcsv      csvq      gomodifytags  impl         reordercsv        staticcheck
cmd         dedupcsv  goplay        pivotcsv     simplehttpserver  transformcsv
comparecsv  diffcsv   gopls         recursecsv   sortcsv
convert     dlv       gotests       recursedata  splitcsv
$ cmd -h
Usage of cmd:
  -author string
        Author; used if -footer is passed
  -font-file string
        path to font file to use
  -font-name string
        Font name ID; e.g 'Helvetica-1251'
  -help
        Show usage message
  -i string
        Input filename or HTTP(s) URL; default is os.Stdin
  -new-page-on-hr
        Interpret HR as a new page; useful for presentations
  -o string
        Output PDF filename; required
  -orientation string
        [portrait | landscape] (default "portrait")
  -page-size string
        [A3 | A4 | A5] (default "A4")
  -s string
        Path to github.com/jessp01/gohighlight/syntax_files
  -theme string
        [light|dark] (default "light")
  -title string
        Presentation title
  -unicode-encoding string
        e.g 'cp1251'
  -with-footer
        Print doc footer (author  title  page number)
$ go install github.com/mandolyte/mdtopdf/cmd/mdtopdf@latest
go: github.com/mandolyte/mdtopdf/cmd/mdtopdf@latest: module github.com/mandolyte/mdtopdf@latest found (v1.5.0), but does not contain package github.com/mandolyte/mdtopdf/cmd/mdtopdf
$ 
```

**Comment by jessp01** [comment]
Hi @mandolyte ,

You've done nothing wrong:) Please see https://github.com/mandolyte/mdtopdf/pull/37

With this, after issuing a new tag, the below should work:
```sh
$ go install github.com/mandolyte/mdtopdf/cmd/md2pdf@latest
```

I had to move `cmd/md2pdf.go` to `cmd/md2pdf/md2pdf.go`, otherwise, the binary is deployed to `$GOBIN/cmd`, which is not what we want.

**Comment by mandolyte** [comment]
@jessp01 - anything aside from signaling to https://pkg.go.dev/github.com/mandolyte/mdtopdf that there is a new release? Sort of feels like overkill to me. Thoughts?

**Comment by jessp01** [comment]
@mandolyte ,

The advantage of using `goreleaser` is that it can produce binaries for multiple archs and GOOS so that one doesn't need the `go` toolchain installed to deploy the application.  You can have a look at the assets in https://github.com/jessp01/zaje/releases/tag/v0.21.4 for example. 

Granted, installing `golang` on any modern OS is fairly easy but still, I reckon it's nice to be able to deploy the binaries without it.

**Comment by mandolyte** [comment]
@jessp01 OK, you convinced me. Go for it!

**Comment by jessp01** [comment]
Hi @mandolyte ,

Just submitted https://github.com/mandolyte/mdtopdf/pull/38. It introduces a GH actions CI and a workflow for creating a package with Goreleaser upon tag creation. 

Either way, I reckon we can close this particular issue as the `go install github.com/mandolyte/mdtopdf/cmd/md2pdf@latest` problem was resolved with commits included in the last tag.

Cheers,

**Comment by mandolyte** [comment]
I think I'll need some guidance on setting up the secret... looking at the
github page at https://github.com/mandolyte/mdtopdf/settings/secrets/actions
and not quite understanding what (if anything) needs to be done.

Thanks!
Cecil

**Comment by jessp01** [comment]
Hi @mandolyte ,

Actually, you don't need to do anything as you've already merged my pull which includes `.github/workflows/go.yml`:)
By doing so, `secrets.GITHUB_TOKEN` was already set.

So really, all you need to do now is create a tag as you normally would and check the log for the job that will be created here https://github.com/mandolyte/mdtopdf/actions
