### ISSUE TITLE
Support for a "book form" PDF

### ISSUE THREAD

**Issue by mandolyte** [mandolyte/mdtopdf#48]
Sorry about the issue title. What I mean specifically is to support multiple markdown files to create one PDF.

This would permit a scenario of writing a book or article with multiple chapters or sections, where each chapter/section is in its own markdown file.

**Comment by jessp01** [comment]
Hi @mandolyte ,

That should be very easy to implement. Although, as we have the `-new-page-on-hr`  option, one could easily concatenate all MD files into one file, with '---'  between each segment to achieve the same result. 

Let me know if you reckon that's not enough or if I've misunderstood your intention.

Cheers,

**Comment by mandolyte** [comment]
That's true. Forgot about that feature you added. Plus, I suspect that if
one is using markdown, then being able to write a script to concentrate the
files together with the rule tucked in-between the files is a skill they
know.

This still might be helpful for those who can't do that. So at best this
idea has low priority.

Thanks for the reminder. I do have a use case for this. I was using pandoc,
but this should be easier

**Comment by jessp01** [comment]
Hi @mandolyte ,

> Thanks for the reminder. I do have a use case for this. I
No worries. Implemented your suggestion here: https://github.com/mandolyte/mdtopdf/pull/51. This is included in the 2.2.3 release.

Cheers,
