### ISSUE TITLE
Unordered list: rectangle instead of dash

### ISSUE THREAD

**Issue by sltu** [mandolyte/mdtopdf#52]
Hi

I am using a common Noto Sans font. For unordered list I am getting this:

![image](https://github.com/mandolyte/mdtopdf/assets/111493050/af2f6d27-2e23-47e4-97f5-235eeee79472)

(the list has one level only)

What could be wrong?

**Comment by jessp01** [comment]
Hi @sltu ,

Please provide the font file used, as well as an MD example and the full command used when generating the PDF.

Cheers,

**Comment by sltu** [comment]
Hi, the same as other issue. It's too late for me.
I changed implementation and I am not using a mdtopdf anymore.

**Comment by jessp01** [comment]
Closing due to lack of info. If you change your mind and want to provide the details as per the above, please do and reopen.
