### ISSUE TITLE
pf.Normal styler is adjusting font in doc only partially 

### ISSUE THREAD

**Issue by sltu** [mandolyte/mdtopdf#53]
Hi, I am setting

```
pf.Normal = mdtopdf.Styler{Font: "notosans", Style: "", Size: 10}
```

and unordered list is rendered correctly, a Noto Sans font is used,
however paragraph text below the list has some other font (Arial?)

![image](https://github.com/mandolyte/mdtopdf/assets/111493050/7411ee32-5fc0-43cf-a54f-06463638144b)

**Comment by jessp01** [comment]
Hi @sltu ,

Please provide the font file used, as well as an MD example and the full command used when generating the PDF (and, if you've made local changes to md2pdf.go or any other bit in the code, include these as well).

Cheers,

**Comment by sltu** [comment]
Hi, it's too late for me.
I changed implementation and I am not using a mdtopdf anymore.

**Comment by jessp01** [comment]
Closing due to lack of info. If you change your mind and want to provide the details as per the above, please do and reopen.
