### ISSUE TITLE
open cp1251.map: no such file or directory

### ISSUE THREAD

**Issue by dcu** [mandolyte/mdtopdf#62]
When using mdtopdf.WithUnicodeTranslator("cp1251") as library I'm getting this error:

`open cp1251.map: no such file or directory`

**Comment by mandolyte** [comment]
The README has this example: https://github.com/mandolyte/mdtopdf?tab=readme-ov-file#using-non-ascii-glyphsfonts

@jessp01 Any thoughts?

**Comment by dcu** [comment]
correct, I found out that that example is outdated, even it doesn't include the theme param.

fpdf doesn't include cp1251.map and that's why it says file not found. but probably the biggest problem is that this library doesn't allow to set the Unicode translator directly.

**Comment by jessp01** [comment]
Hi @dcu ,

> correct, I found out that that example is outdated, even it doesn't include the theme param.
You do not have to specify a theme, if `--theme` isn't passed, the default is light; from the usage message:
```
  -theme string
    	[light|dark] (default "light")
```
> fpdf doesn't include cp1251.map and that's why it says file not found.
cp1251.map is actually included in this repo, see https://github.com/mandolyte/mdtopdf/blob/master/cmd/md2pdf/cp1251.map

> but probably the biggest problem is that this library doesn't allow to set the Unicode translator directly.
Can you elaborate as to what you mean by this?

The example @mandolyte pointed to actually works just fine for me. If you clone the repo (or download the full source archive) and:
```sh
$ cd cmd/md2pdf
$ go build
$ ./md2pdf -i russian.md -o russian.pdf --unicode-encoding cp1251 --font-file helvetica_1251.json --font-name Helvetica_1251
```
You'll get `russian.pdf` with:
# Heading One
Here are lines of Russian:  

- Молоко и творог  
- Съешь же ещё этих мягких французских булок, да выпей чаю 

Or at least, as they say, it works for me:) If the above fails for you, please let me know.

**Comment by jessp01** [comment]
Closing for now but feel free to reopen with more info.

**Comment by ernani** [comment]
Just letting you guys know that the homebrew binary gives me the exact same error about the map file, also, for Brazilian Portuguese and utf-8 encoded Markdown files I am having a hard time trying to understand what value should I use for -unicode-encoding param...
