### ISSUE TITLE
Idea: themed output

### ISSUE THREAD

**Issue by sirnewton01** [mandolyte/mdtopdf#8]
Since markdown has no real styling information and PDF has no real equivalent to after-the-fact styling like CSS it would be interesting if this tool had some theming concept. Out of the box, it would be great to support certain common styles of PDF documents. One example that comes to mind is an academic paper style (e.g. https://arxiv.org/pdf/1801.00013.pdf). Another could be a user guide style that resembles certain common manuals. I think it would also be useful to have some way to add more themes to the tool whether programmatically or declaratively.

**Comment by mandolyte** [comment]
Interesting concept. I think I'll have to review these document styles to see if there is enough between the source markdown and the GOFDF package to map onto the style... sounds like fun. But hope you're not in a hurry. I have some other things I need to work on first.

**Comment by sirnewton01** [comment]
Thanks, I hope that me raising issues is helpful and not an annoyance. No rush at all. If I have time I may experiment myself with the concept. I just hoped to raise it here so that the idea is not forgotten by myself at least. :)

**Comment by mandolyte** [comment]
@sirnewton01 Some work in this area has been done by @jessp01 ... I plan to close this issue once that PR has been merged. Since this will be a fairly significant upgrade, I'll probably make v1.5.0.

Thanks

**Comment by mandolyte** [comment]
Closed by PR #35
